//! Safe access to the peripheral table the shim publishes.
//!
//! Every accessor takes the block's index in model I/O order — the order
//! the generated `hal_data.c` wrote the arrays in, which is the order the block
//! appears in the model. `gpio_output(0)` is the first GPIO block,
//! `pwm(1)` the second PWM block.
//!
//! Nothing can check that agreement: one side is a generated Rust crate, the
//! other a generated XML table, and they meet only at run time. If the two
//! disagree about order, the model drives the wrong pins and nothing reports
//! it. Generating both from the same model description is what makes this safe;
//! hand-editing one of them is where it stops being safe.
//!
//! # Typical use
//!
//! ```ignore
//! let p = Peripherals::take()?;
//! let led = p.gpio_output(0)?;
//! let button = p.gpio_input(1)?;
//! let motor = p.pwm(0)?;
//! ```
//!
//! # Renesas Project Support Code
//!
//! An FSP specific .h/.c  needs to be generated that creates the mapping to
//! the peripherals. For example, a pictorus_data.c file that has a struct for
//! GPIO Pins that looks like:
//! ```ignore
//! static const bsp_io_port_pin_t g_pictorus_gpio_pins[] =
//! {
//!     BSP_IO_PORT_00_PIN_05,             /* [0] GpioInput1  -- SW1  */
//!     BSP_IO_PORT_04_PIN_04,             /* [1] GpioOutput1 -- LED2 */
//! };
//! ```
//!
//! This support code is NOT generated by this crate, as it depends on the FSP
//! project configuration.

use core::sync::atomic::{AtomicBool, Ordering};

use renesas_fsp_sys::bsp_io_port_pin_t;

use crate::app;
use crate::error::{FspError, Result};
use crate::gpio_protocol::{FspInputPin, FspOutputPin, FspPin, Ioport};
use crate::pwm_protocol::{FspPwm, GTIOCA, GTIOCB};

static TAKEN: AtomicBool = AtomicBool::new(false);

/// The peripherals this model was bound to.
pub struct Peripherals {
    bindings: &'static app::rm_pictorus_bindings_t,
    ioport: Ioport,
}

impl Peripherals {
    /// Take the peripheral table, once.
    ///
    /// Fails before `pictorus_rt_bind` has run — that is, if something builds
    /// I/O before the shim's `open()` — and on any call after the first. Both
    /// are configuration mistakes rather than conditions to recover from.
    pub fn take() -> Result<Self> {
        if TAKEN.swap(true, Ordering::AcqRel) {
            return Err(FspError::ALREADY_TAKEN);
        }

        let bindings = app::bindings().ok_or(FspError::NOT_BOUND)?;

        // SAFETY: pictorus_rt_bind's contract makes p_ioport a live
        // `const ioport_instance_t` in the generated hal_data.c, and FSP opened
        // it from R_BSP_WarmStart(POST_C) before main.
        let ioport = unsafe { Ioport::from_instance(bindings.p_ioport) }?;

        Ok(Self { bindings, ioport })
    }

    /// Allow [`Peripherals::take`] to succeed again, after the model's I/O has
    /// been dropped.
    ///
    /// # Safety
    ///
    /// Every wrapper obtained from this `Peripherals` must already have been
    /// dropped. Calling this while one is alive permits a second owner of the
    /// same peripheral, which is exactly what the latch exists to prevent.
    /// The shim satisfies this by calling it only from `app_interface_free`,
    /// after the model has been freed.
    pub unsafe fn release() {
        TAKEN.store(false, Ordering::Release);
    }

    /// The IOPORT singleton, for driving a pin the table does not name.
    pub fn ioport(&self) -> Ioport {
        self.ioport
    }

    /// Every pin identity the configurator supplied, in model order.
    pub fn gpio_pins(&self) -> &'static [bsp_io_port_pin_t] {
        // SAFETY: p_gpio_pins points at gpio_pin_count elements of a const
        // array in the generated hal_data.c, or is null when the count is zero.
        unsafe {
            counted(
                self.bindings.p_gpio_pins,
                self.bindings.gpio_pin_count as usize,
            )
        }
    }

    pub fn gpio_pin(&self, index: usize) -> Result<FspPin> {
        self.gpio_pins()
            .get(index)
            .map(|pin| FspPin::from_raw(pin.0))
            .ok_or(FspError::NO_SUCH_BLOCK)
    }

    /// A pin the model writes.
    ///
    /// Direction is not set here: the Pins tab owns pin mode and `pin_data.c`
    /// applies it before `main`. Asking for an output on a pin left as an input
    /// yields a wrapper that reports success and drives nothing.
    pub fn gpio_output(&self, index: usize) -> Result<FspOutputPin> {
        Ok(FspOutputPin::new(self.ioport, self.gpio_pin(index)?))
    }

    /// A pin the model reads.
    pub fn gpio_input(&self, index: usize) -> Result<FspInputPin> {
        Ok(FspInputPin::new(self.ioport, self.gpio_pin(index)?))
    }

    /// The model's `index`'th PWM output.
    ///
    /// Duty 0 drives the timer's first compare output and duty 1 the second —
    /// GTIOCA and GTIOCB on a GPT, AGTOA and AGTOB on an AGT. A model needing
    /// more than two independent duties needs a second timer and a second PWM
    /// block. Whatever generates `hal_data.c` must assume the same mapping.
    pub fn pwm(&self, index: usize) -> Result<FspPwm> {
        let instance = self.nth(
            self.bindings.pp_pwm,
            self.bindings.pwm_count as usize,
            index,
        )?;
        // SAFETY: pictorus_rt_bind's contract.
        unsafe { FspPwm::open(instance, [Some(GTIOCA), Some(GTIOCB)]) }
    }

    /// The `index`'th entry of a counted array of instance pointers.
    fn nth<T>(&self, array: *const *const T, count: usize, index: usize) -> Result<*const T> {
        if index >= count {
            return Err(FspError::NO_SUCH_BLOCK);
        }
        // SAFETY: the array holds `count` elements and index is in range.
        Ok(unsafe { *array.add(index) })
    }
}

/// A counted array as a slice, tolerating the null-and-zero case.
///
/// `from_raw_parts` requires a non-null aligned pointer even for an empty
/// slice, and the generated table writes `NULL` for a peripheral the model does
/// not use.
///
/// # Safety
///
/// `ptr` must point at `len` initialised elements, or `len` must be zero.
unsafe fn counted<'a, T>(ptr: *const T, len: usize) -> &'a [T] {
    if len == 0 || ptr.is_null() {
        return &[];
    }
    unsafe { core::slice::from_raw_parts(ptr, len) }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The null-and-zero case is what a model with no GPIO blocks produces, and
    /// `from_raw_parts` is UB on a null pointer even for an empty slice.
    #[test]
    fn counted_tolerates_null_with_zero_length() {
        let empty: &[u8] = unsafe { counted(core::ptr::null(), 0) };
        assert!(empty.is_empty());

        // A non-zero count against a null pointer is a malformed table rather
        // than an empty one, but returning empty is the only safe reading.
        let malformed: &[u8] = unsafe { counted(core::ptr::null(), 4) };
        assert!(malformed.is_empty());
    }

    #[test]
    fn counted_exposes_every_element() {
        let pins = [1u16, 2, 3];
        let slice: &[u16] = unsafe { counted(pins.as_ptr(), pins.len()) };
        assert_eq!(slice, &[1, 2, 3]);
    }
}
