[package]
name = "px4-msgs-sys"
version = "0.1.0"
edition = "2024"
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[build-dependencies]
bindgen = "0.72.0"
