/* automatically generated by rust-bindgen 0.72.1 */

pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const FSP_VERSION_MAJOR: u32 = 6;
pub const FSP_VERSION_MINOR: u32 = 6;
pub const FSP_VERSION_PATCH: u32 = 0;
pub const FSP_VERSION_BUILD: u32 = 0;
pub const FSP_VERSION_STRING: &[u8; 6] = b"6.6.0\0";
pub const FSP_VERSION_BUILD_STRING: &[u8; 68] =
    b"Built with Renesas Advanced Flexible Software Package version 6.6.0\0";
#[repr(C)]
#[derive(Copy, Clone)]
pub union st_fsp_pack_version {
    pub version_id: u32,
    pub version_id_b: st_fsp_pack_version_version_id_b_s,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_fsp_pack_version_version_id_b_s {
    pub build: u8,
    pub patch: u8,
    pub minor: u8,
    pub major: u8,
}
pub type fsp_pack_version_t = st_fsp_pack_version;
impl e_fsp_err {
    pub const FSP_SUCCESS: e_fsp_err = e_fsp_err(0);
    pub const FSP_ERR_ASSERTION: e_fsp_err = e_fsp_err(1);
    pub const FSP_ERR_INVALID_POINTER: e_fsp_err = e_fsp_err(2);
    pub const FSP_ERR_INVALID_ARGUMENT: e_fsp_err = e_fsp_err(3);
    pub const FSP_ERR_INVALID_CHANNEL: e_fsp_err = e_fsp_err(4);
    pub const FSP_ERR_INVALID_MODE: e_fsp_err = e_fsp_err(5);
    pub const FSP_ERR_UNSUPPORTED: e_fsp_err = e_fsp_err(6);
    pub const FSP_ERR_NOT_OPEN: e_fsp_err = e_fsp_err(7);
    pub const FSP_ERR_IN_USE: e_fsp_err = e_fsp_err(8);
    pub const FSP_ERR_OUT_OF_MEMORY: e_fsp_err = e_fsp_err(9);
    pub const FSP_ERR_HW_LOCKED: e_fsp_err = e_fsp_err(10);
    pub const FSP_ERR_IRQ_BSP_DISABLED: e_fsp_err = e_fsp_err(11);
    pub const FSP_ERR_OVERFLOW: e_fsp_err = e_fsp_err(12);
    pub const FSP_ERR_UNDERFLOW: e_fsp_err = e_fsp_err(13);
    pub const FSP_ERR_ALREADY_OPEN: e_fsp_err = e_fsp_err(14);
    pub const FSP_ERR_APPROXIMATION: e_fsp_err = e_fsp_err(15);
    pub const FSP_ERR_CLAMPED: e_fsp_err = e_fsp_err(16);
    pub const FSP_ERR_INVALID_RATE: e_fsp_err = e_fsp_err(17);
    pub const FSP_ERR_ABORTED: e_fsp_err = e_fsp_err(18);
    pub const FSP_ERR_NOT_ENABLED: e_fsp_err = e_fsp_err(19);
    pub const FSP_ERR_TIMEOUT: e_fsp_err = e_fsp_err(20);
    pub const FSP_ERR_INVALID_BLOCKS: e_fsp_err = e_fsp_err(21);
    pub const FSP_ERR_INVALID_ADDRESS: e_fsp_err = e_fsp_err(22);
    pub const FSP_ERR_INVALID_SIZE: e_fsp_err = e_fsp_err(23);
    pub const FSP_ERR_WRITE_FAILED: e_fsp_err = e_fsp_err(24);
    pub const FSP_ERR_ERASE_FAILED: e_fsp_err = e_fsp_err(25);
    pub const FSP_ERR_INVALID_CALL: e_fsp_err = e_fsp_err(26);
    pub const FSP_ERR_INVALID_HW_CONDITION: e_fsp_err = e_fsp_err(27);
    pub const FSP_ERR_INVALID_FACTORY_FLASH: e_fsp_err = e_fsp_err(28);
    pub const FSP_ERR_INVALID_STATE: e_fsp_err = e_fsp_err(30);
    pub const FSP_ERR_NOT_ERASED: e_fsp_err = e_fsp_err(31);
    pub const FSP_ERR_SECTOR_RELEASE_FAILED: e_fsp_err = e_fsp_err(32);
    pub const FSP_ERR_NOT_INITIALIZED: e_fsp_err = e_fsp_err(33);
    pub const FSP_ERR_NOT_FOUND: e_fsp_err = e_fsp_err(34);
    pub const FSP_ERR_NO_CALLBACK_MEMORY: e_fsp_err = e_fsp_err(35);
    pub const FSP_ERR_BUFFER_EMPTY: e_fsp_err = e_fsp_err(36);
    pub const FSP_ERR_INVALID_DATA: e_fsp_err = e_fsp_err(37);
    pub const FSP_ERR_INTERNAL: e_fsp_err = e_fsp_err(100);
    pub const FSP_ERR_WAIT_ABORTED: e_fsp_err = e_fsp_err(101);
    pub const FSP_ERR_FRAMING: e_fsp_err = e_fsp_err(200);
    pub const FSP_ERR_BREAK_DETECT: e_fsp_err = e_fsp_err(201);
    pub const FSP_ERR_PARITY: e_fsp_err = e_fsp_err(202);
    pub const FSP_ERR_RXBUF_OVERFLOW: e_fsp_err = e_fsp_err(203);
    pub const FSP_ERR_QUEUE_UNAVAILABLE: e_fsp_err = e_fsp_err(204);
    pub const FSP_ERR_INSUFFICIENT_SPACE: e_fsp_err = e_fsp_err(205);
    pub const FSP_ERR_INSUFFICIENT_DATA: e_fsp_err = e_fsp_err(206);
    pub const FSP_ERR_TRANSFER_ABORTED: e_fsp_err = e_fsp_err(300);
    pub const FSP_ERR_MODE_FAULT: e_fsp_err = e_fsp_err(301);
    pub const FSP_ERR_READ_OVERFLOW: e_fsp_err = e_fsp_err(302);
    pub const FSP_ERR_SPI_PARITY: e_fsp_err = e_fsp_err(303);
    pub const FSP_ERR_OVERRUN: e_fsp_err = e_fsp_err(304);
    pub const FSP_ERR_CLOCK_INACTIVE: e_fsp_err = e_fsp_err(400);
    pub const FSP_ERR_CLOCK_ACTIVE: e_fsp_err = e_fsp_err(401);
    pub const FSP_ERR_NOT_STABILIZED: e_fsp_err = e_fsp_err(403);
    pub const FSP_ERR_PLL_SRC_INACTIVE: e_fsp_err = e_fsp_err(404);
    pub const FSP_ERR_OSC_STOP_DET_ENABLED: e_fsp_err = e_fsp_err(405);
    pub const FSP_ERR_OSC_STOP_DETECTED: e_fsp_err = e_fsp_err(406);
    pub const FSP_ERR_OSC_STOP_CLOCK_ACTIVE: e_fsp_err = e_fsp_err(407);
    pub const FSP_ERR_CLKOUT_EXCEEDED: e_fsp_err = e_fsp_err(408);
    pub const FSP_ERR_USB_MODULE_ENABLED: e_fsp_err = e_fsp_err(409);
    pub const FSP_ERR_HARDWARE_TIMEOUT: e_fsp_err = e_fsp_err(410);
    pub const FSP_ERR_LOW_VOLTAGE_MODE: e_fsp_err = e_fsp_err(411);
    pub const FSP_ERR_PE_FAILURE: e_fsp_err = e_fsp_err(500);
    pub const FSP_ERR_CMD_LOCKED: e_fsp_err = e_fsp_err(501);
    pub const FSP_ERR_FCLK: e_fsp_err = e_fsp_err(502);
    pub const FSP_ERR_INVALID_LINKED_ADDRESS: e_fsp_err = e_fsp_err(503);
    pub const FSP_ERR_BLANK_CHECK_FAILED: e_fsp_err = e_fsp_err(504);
    pub const FSP_ERR_HUK_ZEROIZATION: e_fsp_err = e_fsp_err(505);
    pub const FSP_ERR_INVALID_CAC_REF_CLOCK: e_fsp_err = e_fsp_err(600);
    pub const FSP_ERR_INVALID_RESULT: e_fsp_err = e_fsp_err(700);
    pub const FSP_ERR_CLOCK_GENERATION: e_fsp_err = e_fsp_err(1000);
    pub const FSP_ERR_INVALID_TIMING_SETTING: e_fsp_err = e_fsp_err(1001);
    pub const FSP_ERR_INVALID_LAYER_SETTING: e_fsp_err = e_fsp_err(1002);
    pub const FSP_ERR_INVALID_ALIGNMENT: e_fsp_err = e_fsp_err(1003);
    pub const FSP_ERR_INVALID_GAMMA_SETTING: e_fsp_err = e_fsp_err(1004);
    pub const FSP_ERR_INVALID_LAYER_FORMAT: e_fsp_err = e_fsp_err(1005);
    pub const FSP_ERR_INVALID_UPDATE_TIMING: e_fsp_err = e_fsp_err(1006);
    pub const FSP_ERR_INVALID_CLUT_ACCESS: e_fsp_err = e_fsp_err(1007);
    pub const FSP_ERR_INVALID_FADE_SETTING: e_fsp_err = e_fsp_err(1008);
    pub const FSP_ERR_INVALID_BRIGHTNESS_SETTING: e_fsp_err = e_fsp_err(1009);
    pub const FSP_ERR_JPEG_ERR: e_fsp_err = e_fsp_err(1100);
    pub const FSP_ERR_JPEG_SOI_NOT_DETECTED: e_fsp_err = e_fsp_err(1101);
    pub const FSP_ERR_JPEG_SOF1_TO_SOFF_DETECTED: e_fsp_err = e_fsp_err(1102);
    pub const FSP_ERR_JPEG_UNSUPPORTED_PIXEL_FORMAT: e_fsp_err = e_fsp_err(1103);
    pub const FSP_ERR_JPEG_SOF_ACCURACY_ERROR: e_fsp_err = e_fsp_err(1104);
    pub const FSP_ERR_JPEG_DQT_ACCURACY_ERROR: e_fsp_err = e_fsp_err(1105);
    pub const FSP_ERR_JPEG_COMPONENT_ERROR1: e_fsp_err = e_fsp_err(1106);
    pub const FSP_ERR_JPEG_COMPONENT_ERROR2: e_fsp_err = e_fsp_err(1107);
    pub const FSP_ERR_JPEG_SOF0_DQT_DHT_NOT_DETECTED: e_fsp_err = e_fsp_err(1108);
    pub const FSP_ERR_JPEG_SOS_NOT_DETECTED: e_fsp_err = e_fsp_err(1109);
    pub const FSP_ERR_JPEG_EOI_NOT_DETECTED: e_fsp_err = e_fsp_err(1110);
    pub const FSP_ERR_JPEG_RESTART_INTERVAL_DATA_NUMBER_ERROR: e_fsp_err = e_fsp_err(1111);
    pub const FSP_ERR_JPEG_IMAGE_SIZE_ERROR: e_fsp_err = e_fsp_err(1112);
    pub const FSP_ERR_JPEG_LAST_MCU_DATA_NUMBER_ERROR: e_fsp_err = e_fsp_err(1113);
    pub const FSP_ERR_JPEG_BLOCK_DATA_NUMBER_ERROR: e_fsp_err = e_fsp_err(1114);
    pub const FSP_ERR_JPEG_BUFFERSIZE_NOT_ENOUGH: e_fsp_err = e_fsp_err(1115);
    pub const FSP_ERR_JPEG_UNSUPPORTED_IMAGE_SIZE: e_fsp_err = e_fsp_err(1116);
    pub const FSP_ERR_CALIBRATE_FAILED: e_fsp_err = e_fsp_err(1200);
    pub const FSP_ERR_IIRFA_ECC_1BIT: e_fsp_err = e_fsp_err(1300);
    pub const FSP_ERR_IIRFA_ECC_2BIT: e_fsp_err = e_fsp_err(1301);
    pub const FSP_ERR_IP_HARDWARE_NOT_PRESENT: e_fsp_err = e_fsp_err(1400);
    pub const FSP_ERR_IP_UNIT_NOT_PRESENT: e_fsp_err = e_fsp_err(1401);
    pub const FSP_ERR_IP_CHANNEL_NOT_PRESENT: e_fsp_err = e_fsp_err(1402);
    pub const FSP_ERR_USB_FAILED: e_fsp_err = e_fsp_err(1500);
    pub const FSP_ERR_USB_BUSY: e_fsp_err = e_fsp_err(1501);
    pub const FSP_ERR_USB_SIZE_SHORT: e_fsp_err = e_fsp_err(1502);
    pub const FSP_ERR_USB_SIZE_OVER: e_fsp_err = e_fsp_err(1503);
    pub const FSP_ERR_USB_NOT_OPEN: e_fsp_err = e_fsp_err(1504);
    pub const FSP_ERR_USB_NOT_SUSPEND: e_fsp_err = e_fsp_err(1505);
    pub const FSP_ERR_USB_PARAMETER: e_fsp_err = e_fsp_err(1506);
    pub const FSP_ERR_NO_MORE_BUFFER: e_fsp_err = e_fsp_err(2000);
    pub const FSP_ERR_ILLEGAL_BUFFER_ADDRESS: e_fsp_err = e_fsp_err(2001);
    pub const FSP_ERR_INVALID_WORKBUFFER_SIZE: e_fsp_err = e_fsp_err(2002);
    pub const FSP_ERR_INVALID_MSG_BUFFER_SIZE: e_fsp_err = e_fsp_err(2003);
    pub const FSP_ERR_TOO_MANY_BUFFERS: e_fsp_err = e_fsp_err(2004);
    pub const FSP_ERR_NO_SUBSCRIBER_FOUND: e_fsp_err = e_fsp_err(2005);
    pub const FSP_ERR_MESSAGE_QUEUE_EMPTY: e_fsp_err = e_fsp_err(2006);
    pub const FSP_ERR_MESSAGE_QUEUE_FULL: e_fsp_err = e_fsp_err(2007);
    pub const FSP_ERR_ILLEGAL_SUBSCRIBER_LISTS: e_fsp_err = e_fsp_err(2008);
    pub const FSP_ERR_BUFFER_RELEASED: e_fsp_err = e_fsp_err(2009);
    pub const FSP_ERR_D2D_ERROR_INIT: e_fsp_err = e_fsp_err(3000);
    pub const FSP_ERR_D2D_ERROR_DEINIT: e_fsp_err = e_fsp_err(3001);
    pub const FSP_ERR_D2D_ERROR_RENDERING: e_fsp_err = e_fsp_err(3002);
    pub const FSP_ERR_D2D_ERROR_SIZE: e_fsp_err = e_fsp_err(3003);
    pub const FSP_ERR_ETHER_ERROR_NO_DATA: e_fsp_err = e_fsp_err(4000);
    pub const FSP_ERR_ETHER_ERROR_LINK: e_fsp_err = e_fsp_err(4001);
    pub const FSP_ERR_ETHER_ERROR_MAGIC_PACKET_MODE: e_fsp_err = e_fsp_err(4002);
    pub const FSP_ERR_ETHER_ERROR_TRANSMIT_BUFFER_FULL: e_fsp_err = e_fsp_err(4003);
    pub const FSP_ERR_ETHER_ERROR_FILTERING: e_fsp_err = e_fsp_err(4004);
    pub const FSP_ERR_ETHER_ERROR_PHY_COMMUNICATION: e_fsp_err = e_fsp_err(4005);
    pub const FSP_ERR_ETHER_RECEIVE_BUFFER_ACTIVE: e_fsp_err = e_fsp_err(4006);
    pub const FSP_ERR_ETHER_PHY_ERROR_LINK: e_fsp_err = e_fsp_err(5000);
    pub const FSP_ERR_ETHER_PHY_NOT_READY: e_fsp_err = e_fsp_err(5001);
    pub const FSP_ERR_QUEUE_FULL: e_fsp_err = e_fsp_err(10000);
    pub const FSP_ERR_QUEUE_EMPTY: e_fsp_err = e_fsp_err(10001);
    pub const FSP_ERR_CTSU_SCANNING: e_fsp_err = e_fsp_err(6000);
    pub const FSP_ERR_CTSU_NOT_GET_DATA: e_fsp_err = e_fsp_err(6001);
    pub const FSP_ERR_CTSU_INCOMPLETE_TUNING: e_fsp_err = e_fsp_err(6002);
    pub const FSP_ERR_CTSU_DIAG_NOT_YET: e_fsp_err = e_fsp_err(6003);
    pub const FSP_ERR_CTSU_DIAG_LDO_OVER_VOLTAGE: e_fsp_err = e_fsp_err(6004);
    pub const FSP_ERR_CTSU_DIAG_CCO_HIGH: e_fsp_err = e_fsp_err(6005);
    pub const FSP_ERR_CTSU_DIAG_CCO_LOW: e_fsp_err = e_fsp_err(6006);
    pub const FSP_ERR_CTSU_DIAG_SSCG: e_fsp_err = e_fsp_err(6007);
    pub const FSP_ERR_CTSU_DIAG_DAC: e_fsp_err = e_fsp_err(6008);
    pub const FSP_ERR_CTSU_DIAG_OUTPUT_VOLTAGE: e_fsp_err = e_fsp_err(6009);
    pub const FSP_ERR_CTSU_DIAG_OVER_VOLTAGE: e_fsp_err = e_fsp_err(6010);
    pub const FSP_ERR_CTSU_DIAG_OVER_CURRENT: e_fsp_err = e_fsp_err(6011);
    pub const FSP_ERR_CTSU_DIAG_LOAD_RESISTANCE: e_fsp_err = e_fsp_err(6012);
    pub const FSP_ERR_CTSU_DIAG_CURRENT_SOURCE: e_fsp_err = e_fsp_err(6013);
    pub const FSP_ERR_CTSU_DIAG_SENSCLK_GAIN: e_fsp_err = e_fsp_err(6014);
    pub const FSP_ERR_CTSU_DIAG_SUCLK_GAIN: e_fsp_err = e_fsp_err(6015);
    pub const FSP_ERR_CTSU_DIAG_CLOCK_RECOVERY: e_fsp_err = e_fsp_err(6016);
    pub const FSP_ERR_CTSU_DIAG_CFC_GAIN: e_fsp_err = e_fsp_err(6017);
    pub const FSP_ERR_CARD_INIT_FAILED: e_fsp_err = e_fsp_err(40000);
    pub const FSP_ERR_CARD_NOT_INSERTED: e_fsp_err = e_fsp_err(40001);
    pub const FSP_ERR_DEVICE_BUSY: e_fsp_err = e_fsp_err(40002);
    pub const FSP_ERR_CARD_NOT_INITIALIZED: e_fsp_err = e_fsp_err(40004);
    pub const FSP_ERR_CARD_WRITE_PROTECTED: e_fsp_err = e_fsp_err(40005);
    pub const FSP_ERR_TRANSFER_BUSY: e_fsp_err = e_fsp_err(40006);
    pub const FSP_ERR_RESPONSE: e_fsp_err = e_fsp_err(40007);
    pub const FSP_ERR_MEDIA_FORMAT_FAILED: e_fsp_err = e_fsp_err(50000);
    pub const FSP_ERR_MEDIA_OPEN_FAILED: e_fsp_err = e_fsp_err(50001);
    pub const FSP_ERR_CAN_DATA_UNAVAILABLE: e_fsp_err = e_fsp_err(60000);
    pub const FSP_ERR_CAN_MODE_SWITCH_FAILED: e_fsp_err = e_fsp_err(60001);
    pub const FSP_ERR_CAN_INIT_FAILED: e_fsp_err = e_fsp_err(60002);
    pub const FSP_ERR_CAN_TRANSMIT_NOT_READY: e_fsp_err = e_fsp_err(60003);
    pub const FSP_ERR_CAN_RECEIVE_MAILBOX: e_fsp_err = e_fsp_err(60004);
    pub const FSP_ERR_CAN_TRANSMIT_MAILBOX: e_fsp_err = e_fsp_err(60005);
    pub const FSP_ERR_CAN_MESSAGE_LOST: e_fsp_err = e_fsp_err(60006);
    pub const FSP_ERR_CAN_TRANSMIT_FIFO_FULL: e_fsp_err = e_fsp_err(60007);
    pub const FSP_ERR_WIFI_CONFIG_FAILED: e_fsp_err = e_fsp_err(70000);
    pub const FSP_ERR_WIFI_INIT_FAILED: e_fsp_err = e_fsp_err(70001);
    pub const FSP_ERR_WIFI_TRANSMIT_FAILED: e_fsp_err = e_fsp_err(70002);
    pub const FSP_ERR_WIFI_INVALID_MODE: e_fsp_err = e_fsp_err(70003);
    pub const FSP_ERR_WIFI_FAILED: e_fsp_err = e_fsp_err(70004);
    pub const FSP_ERR_WIFI_SCAN_COMPLETE: e_fsp_err = e_fsp_err(70005);
    pub const FSP_ERR_WIFI_AP_NOT_CONNECTED: e_fsp_err = e_fsp_err(70006);
    pub const FSP_ERR_WIFI_UNKNOWN_AT_CMD: e_fsp_err = e_fsp_err(70007);
    pub const FSP_ERR_WIFI_INSUF_PARAM: e_fsp_err = e_fsp_err(70008);
    pub const FSP_ERR_WIFI_TOO_MANY_PARAMS: e_fsp_err = e_fsp_err(70009);
    pub const FSP_ERR_WIFI_INV_PARAM_VAL: e_fsp_err = e_fsp_err(70010);
    pub const FSP_ERR_WIFI_NO_RESULT: e_fsp_err = e_fsp_err(70011);
    pub const FSP_ERR_WIFI_RSP_BUF_OVFLW: e_fsp_err = e_fsp_err(70012);
    pub const FSP_ERR_WIFI_FUNC_NOT_CONFIG: e_fsp_err = e_fsp_err(70013);
    pub const FSP_ERR_WIFI_NVRAM_WR_FAIL: e_fsp_err = e_fsp_err(70014);
    pub const FSP_ERR_WIFI_RET_MEM_WR_FAIL: e_fsp_err = e_fsp_err(70015);
    pub const FSP_ERR_WIFI_UNKNOWN_ERR: e_fsp_err = e_fsp_err(70016);
    pub const FSP_ERR_CELLULAR_CONFIG_FAILED: e_fsp_err = e_fsp_err(80000);
    pub const FSP_ERR_CELLULAR_INIT_FAILED: e_fsp_err = e_fsp_err(80001);
    pub const FSP_ERR_CELLULAR_TRANSMIT_FAILED: e_fsp_err = e_fsp_err(80002);
    pub const FSP_ERR_CELLULAR_FW_UPTODATE: e_fsp_err = e_fsp_err(80003);
    pub const FSP_ERR_CELLULAR_FW_UPGRADE_FAILED: e_fsp_err = e_fsp_err(80004);
    pub const FSP_ERR_CELLULAR_FAILED: e_fsp_err = e_fsp_err(80005);
    pub const FSP_ERR_CELLULAR_INVALID_STATE: e_fsp_err = e_fsp_err(80006);
    pub const FSP_ERR_CELLULAR_REGISTRATION_FAILED: e_fsp_err = e_fsp_err(80007);
    pub const FSP_ERR_BLE_FAILED: e_fsp_err = e_fsp_err(90001);
    pub const FSP_ERR_BLE_INIT_FAILED: e_fsp_err = e_fsp_err(90002);
    pub const FSP_ERR_BLE_CONFIG_FAILED: e_fsp_err = e_fsp_err(90003);
    pub const FSP_ERR_BLE_PRF_ALREADY_ENABLED: e_fsp_err = e_fsp_err(90004);
    pub const FSP_ERR_BLE_PRF_NOT_ENABLED: e_fsp_err = e_fsp_err(90005);
    pub const FSP_ERR_BLE_ABS_INVALID_OPERATION: e_fsp_err = e_fsp_err(91001);
    pub const FSP_ERR_BLE_ABS_NOT_FOUND: e_fsp_err = e_fsp_err(91002);
    pub const FSP_ERR_CRYPTO_CONTINUE: e_fsp_err = e_fsp_err(65536);
    pub const FSP_ERR_CRYPTO_SCE_RESOURCE_CONFLICT: e_fsp_err = e_fsp_err(65537);
    pub const FSP_ERR_CRYPTO_SCE_FAIL: e_fsp_err = e_fsp_err(65538);
    pub const FSP_ERR_CRYPTO_SCE_HRK_INVALID_INDEX: e_fsp_err = e_fsp_err(65539);
    pub const FSP_ERR_CRYPTO_SCE_RETRY: e_fsp_err = e_fsp_err(65540);
    pub const FSP_ERR_CRYPTO_SCE_VERIFY_FAIL: e_fsp_err = e_fsp_err(65541);
    pub const FSP_ERR_CRYPTO_SCE_ALREADY_OPEN: e_fsp_err = e_fsp_err(65542);
    pub const FSP_ERR_CRYPTO_NOT_OPEN: e_fsp_err = e_fsp_err(65543);
    pub const FSP_ERR_CRYPTO_UNKNOWN: e_fsp_err = e_fsp_err(65544);
    pub const FSP_ERR_CRYPTO_NULL_POINTER: e_fsp_err = e_fsp_err(65545);
    pub const FSP_ERR_CRYPTO_NOT_IMPLEMENTED: e_fsp_err = e_fsp_err(65546);
    pub const FSP_ERR_CRYPTO_RNG_INVALID_PARAM: e_fsp_err = e_fsp_err(65547);
    pub const FSP_ERR_CRYPTO_RNG_FATAL_ERROR: e_fsp_err = e_fsp_err(65548);
    pub const FSP_ERR_CRYPTO_INVALID_SIZE: e_fsp_err = e_fsp_err(65549);
    pub const FSP_ERR_CRYPTO_INVALID_STATE: e_fsp_err = e_fsp_err(65550);
    pub const FSP_ERR_CRYPTO_ALREADY_OPEN: e_fsp_err = e_fsp_err(65551);
    pub const FSP_ERR_CRYPTO_INSTALL_KEY_FAILED: e_fsp_err = e_fsp_err(65552);
    pub const FSP_ERR_CRYPTO_AUTHENTICATION_FAILED: e_fsp_err = e_fsp_err(65553);
    pub const FSP_ERR_CRYPTO_SCE_KEY_SET_FAIL: e_fsp_err = e_fsp_err(65554);
    pub const FSP_ERR_CRYPTO_SCE_AUTHENTICATION: e_fsp_err = e_fsp_err(65555);
    pub const FSP_ERR_CRYPTO_SCE_PARAMETER: e_fsp_err = e_fsp_err(65556);
    pub const FSP_ERR_CRYPTO_SCE_PROHIBIT_FUNCTION: e_fsp_err = e_fsp_err(65557);
    pub const FSP_ERR_CRYPTO_SCE_PASS_1: e_fsp_err = e_fsp_err(65558);
    pub const FSP_ERR_CRYPTO_SCE_PASS_2: e_fsp_err = e_fsp_err(65559);
    pub const FSP_ERR_CRYPTO_SCE_LBIST_CHECK_BUSY: e_fsp_err = e_fsp_err(65791);
    pub const FSP_ERR_CRYPTO_RSIP_RESOURCE_CONFLICT: e_fsp_err = e_fsp_err(65792);
    pub const FSP_ERR_CRYPTO_RSIP_FATAL: e_fsp_err = e_fsp_err(65793);
    pub const FSP_ERR_CRYPTO_RSIP_FAIL: e_fsp_err = e_fsp_err(65794);
    pub const FSP_ERR_CRYPTO_RSIP_KEY_SET_FAIL: e_fsp_err = e_fsp_err(65795);
    pub const FSP_ERR_CRYPTO_RSIP_AUTHENTICATION: e_fsp_err = e_fsp_err(65796);
    pub const FSP_ERR_CRYPTO_RSIP_DLMS_ERROR: e_fsp_err = e_fsp_err(65797);
    pub const FSP_ERR_CRYPTO_RSIP_LBIST_CHECK_BUSY: e_fsp_err = e_fsp_err(66047);
    pub const FSP_ERR_CRYPTO_COMMON_NOT_OPENED: e_fsp_err = e_fsp_err(131072);
    pub const FSP_ERR_CRYPTO_HAL_ERROR: e_fsp_err = e_fsp_err(131073);
    pub const FSP_ERR_CRYPTO_KEY_BUF_NOT_ENOUGH: e_fsp_err = e_fsp_err(131074);
    pub const FSP_ERR_CRYPTO_BUF_OVERFLOW: e_fsp_err = e_fsp_err(131075);
    pub const FSP_ERR_CRYPTO_INVALID_OPERATION_MODE: e_fsp_err = e_fsp_err(131076);
    pub const FSP_ERR_MESSAGE_TOO_LONG: e_fsp_err = e_fsp_err(131077);
    pub const FSP_ERR_RSA_DECRYPTION_ERROR: e_fsp_err = e_fsp_err(131078);
    pub const FSP_ERR_SENSOR_INVALID_DATA: e_fsp_err = e_fsp_err(196608);
    pub const FSP_ERR_SENSOR_IN_STABILIZATION: e_fsp_err = e_fsp_err(196609);
    pub const FSP_ERR_SENSOR_MEASUREMENT_NOT_FINISHED: e_fsp_err = e_fsp_err(196610);
    pub const FSP_ERR_COMMS_BUS_NOT_OPEN: e_fsp_err = e_fsp_err(262144);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_fsp_err(pub core::ffi::c_uint);
pub use self::e_fsp_err as fsp_err_t;
impl IRQn {
    pub const Reset_IRQn: IRQn = IRQn(-15);
    pub const NonMaskableInt_IRQn: IRQn = IRQn(-14);
    pub const HardFault_IRQn: IRQn = IRQn(-13);
    pub const MemoryManagement_IRQn: IRQn = IRQn(-12);
    pub const BusFault_IRQn: IRQn = IRQn(-11);
    pub const UsageFault_IRQn: IRQn = IRQn(-10);
    pub const SecureFault_IRQn: IRQn = IRQn(-9);
    pub const SVCall_IRQn: IRQn = IRQn(-5);
    pub const DebugMonitor_IRQn: IRQn = IRQn(-4);
    pub const PendSV_IRQn: IRQn = IRQn(-2);
    pub const SysTick_IRQn: IRQn = IRQn(-1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct IRQn(pub core::ffi::c_schar);
pub use self::IRQn as IRQn_Type;
impl e_bsp_io_level {
    pub const BSP_IO_LEVEL_LOW: e_bsp_io_level = e_bsp_io_level(0);
    pub const BSP_IO_LEVEL_HIGH: e_bsp_io_level = e_bsp_io_level(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_bsp_io_level(pub core::ffi::c_uchar);
pub use self::e_bsp_io_level as bsp_io_level_t;
impl e_bsp_io_port {
    pub const BSP_IO_PORT_00: e_bsp_io_port = e_bsp_io_port(0);
    pub const BSP_IO_PORT_14: e_bsp_io_port = e_bsp_io_port(3584);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_bsp_io_port(pub core::ffi::c_ushort);
pub use self::e_bsp_io_port as bsp_io_port_t;
impl e_bsp_io_port_pin_t {
    pub const BSP_IO_PORT_00_PIN_00: e_bsp_io_port_pin_t = e_bsp_io_port_pin_t(0);
    pub const BSP_IO_PORT_FF_PIN_FF: e_bsp_io_port_pin_t = e_bsp_io_port_pin_t(65535);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_bsp_io_port_pin_t(pub core::ffi::c_ushort);
pub use self::e_bsp_io_port_pin_t as bsp_io_port_pin_t;
impl e_bsp_delay_units {
    pub const BSP_DELAY_UNITS_SECONDS: e_bsp_delay_units = e_bsp_delay_units(1000000);
    pub const BSP_DELAY_UNITS_MILLISECONDS: e_bsp_delay_units = e_bsp_delay_units(1000);
    pub const BSP_DELAY_UNITS_MICROSECONDS: e_bsp_delay_units = e_bsp_delay_units(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_bsp_delay_units(pub core::ffi::c_uint);
pub use self::e_bsp_delay_units as bsp_delay_units_t;
unsafe extern "C" {
    pub fn R_BSP_SoftwareDelay(delay: u32, units: bsp_delay_units_t);
}
unsafe extern "C" {
    pub fn R_FSP_VersionGet(p_version: *mut fsp_pack_version_t) -> fsp_err_t;
}
pub type ioport_size_t = u16;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_ioport_pin_cfg {
    pub pin_cfg: u32,
    pub pin: bsp_io_port_pin_t,
}
pub type ioport_pin_cfg_t = st_ioport_pin_cfg;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_ioport_cfg {
    pub number_of_pins: u16,
    pub p_pin_cfg_data: *const ioport_pin_cfg_t,
    pub p_extend: *const core::ffi::c_void,
}
pub type ioport_cfg_t = st_ioport_cfg;
pub type ioport_ctrl_t = core::ffi::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_ioport_api {
    pub open: ::core::option::Option<
        unsafe extern "C" fn(p_ctrl: *mut ioport_ctrl_t, p_cfg: *const ioport_cfg_t) -> fsp_err_t,
    >,
    pub close:
        ::core::option::Option<unsafe extern "C" fn(p_ctrl: *mut ioport_ctrl_t) -> fsp_err_t>,
    pub pinsCfg: ::core::option::Option<
        unsafe extern "C" fn(p_ctrl: *mut ioport_ctrl_t, p_cfg: *const ioport_cfg_t) -> fsp_err_t,
    >,
    pub pinCfg: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut ioport_ctrl_t,
            pin: bsp_io_port_pin_t,
            cfg: u32,
        ) -> fsp_err_t,
    >,
    pub pinEventInputRead: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut ioport_ctrl_t,
            pin: bsp_io_port_pin_t,
            p_pin_event: *mut bsp_io_level_t,
        ) -> fsp_err_t,
    >,
    pub pinEventOutputWrite: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut ioport_ctrl_t,
            pin: bsp_io_port_pin_t,
            pin_value: bsp_io_level_t,
        ) -> fsp_err_t,
    >,
    pub pinRead: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut ioport_ctrl_t,
            pin: bsp_io_port_pin_t,
            p_pin_value: *mut bsp_io_level_t,
        ) -> fsp_err_t,
    >,
    pub pinWrite: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut ioport_ctrl_t,
            pin: bsp_io_port_pin_t,
            level: bsp_io_level_t,
        ) -> fsp_err_t,
    >,
    pub portDirectionSet: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut ioport_ctrl_t,
            port: bsp_io_port_t,
            direction_values: ioport_size_t,
            mask: ioport_size_t,
        ) -> fsp_err_t,
    >,
    pub portEventInputRead: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut ioport_ctrl_t,
            port: bsp_io_port_t,
            p_event_data: *mut ioport_size_t,
        ) -> fsp_err_t,
    >,
    pub portEventOutputWrite: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut ioport_ctrl_t,
            port: bsp_io_port_t,
            event_data: ioport_size_t,
            mask_value: ioport_size_t,
        ) -> fsp_err_t,
    >,
    pub portRead: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut ioport_ctrl_t,
            port: bsp_io_port_t,
            p_port_value: *mut ioport_size_t,
        ) -> fsp_err_t,
    >,
    pub portWrite: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut ioport_ctrl_t,
            port: bsp_io_port_t,
            value: ioport_size_t,
            mask: ioport_size_t,
        ) -> fsp_err_t,
    >,
}
pub type ioport_api_t = st_ioport_api;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_ioport_instance {
    pub p_ctrl: *mut ioport_ctrl_t,
    pub p_cfg: *const ioport_cfg_t,
    pub p_api: *const ioport_api_t,
}
pub type ioport_instance_t = st_ioport_instance;
impl e_timer_event {
    pub const TIMER_EVENT_CYCLE_END: e_timer_event = e_timer_event(0);
    pub const TIMER_EVENT_CREST: e_timer_event = e_timer_event(0);
    pub const TIMER_EVENT_CAPTURE_A: e_timer_event = e_timer_event(1);
    pub const TIMER_EVENT_CAPTURE_B: e_timer_event = e_timer_event(2);
    pub const TIMER_EVENT_TROUGH: e_timer_event = e_timer_event(3);
    pub const TIMER_EVENT_COMPARE_A: e_timer_event = e_timer_event(4);
    pub const TIMER_EVENT_COMPARE_B: e_timer_event = e_timer_event(5);
    pub const TIMER_EVENT_COMPARE_C: e_timer_event = e_timer_event(6);
    pub const TIMER_EVENT_COMPARE_D: e_timer_event = e_timer_event(7);
    pub const TIMER_EVENT_COMPARE_E: e_timer_event = e_timer_event(8);
    pub const TIMER_EVENT_COMPARE_F: e_timer_event = e_timer_event(9);
    pub const TIMER_EVENT_DEAD_TIME: e_timer_event = e_timer_event(10);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_timer_event(pub core::ffi::c_uchar);
pub use self::e_timer_event as timer_event_t;
impl e_timer_variant {
    pub const TIMER_VARIANT_32_BIT: e_timer_variant = e_timer_variant(0);
    pub const TIMER_VARIANT_16_BIT: e_timer_variant = e_timer_variant(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_timer_variant(pub core::ffi::c_uchar);
pub use self::e_timer_variant as timer_variant_t;
impl e_timer_compare_match {
    pub const TIMER_COMPARE_MATCH_A: e_timer_compare_match = e_timer_compare_match(0);
    pub const TIMER_COMPARE_MATCH_B: e_timer_compare_match = e_timer_compare_match(1);
    pub const TIMER_COMPARE_MATCH_C: e_timer_compare_match = e_timer_compare_match(2);
    pub const TIMER_COMPARE_MATCH_D: e_timer_compare_match = e_timer_compare_match(3);
    pub const TIMER_COMPARE_MATCH_E: e_timer_compare_match = e_timer_compare_match(4);
    pub const TIMER_COMPARE_MATCH_F: e_timer_compare_match = e_timer_compare_match(5);
    pub const TIMER_COMPARE_MATCH_G: e_timer_compare_match = e_timer_compare_match(6);
    pub const TIMER_COMPARE_MATCH_H: e_timer_compare_match = e_timer_compare_match(7);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_timer_compare_match(pub core::ffi::c_uchar);
pub use self::e_timer_compare_match as timer_compare_match_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_timer_callback_args {
    pub p_context: *mut core::ffi::c_void,
    pub event: timer_event_t,
    pub capture: u32,
}
pub type timer_callback_args_t = st_timer_callback_args;
pub type timer_ctrl_t = core::ffi::c_void;
impl e_timer_state {
    pub const TIMER_STATE_STOPPED: e_timer_state = e_timer_state(0);
    pub const TIMER_STATE_COUNTING: e_timer_state = e_timer_state(1);
    pub const TIMER_STATE_UNKNOWN: e_timer_state = e_timer_state(2);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_timer_state(pub core::ffi::c_uchar);
pub use self::e_timer_state as timer_state_t;
impl e_timer_mode {
    pub const TIMER_MODE_PERIODIC: e_timer_mode = e_timer_mode(0);
    pub const TIMER_MODE_ONE_SHOT: e_timer_mode = e_timer_mode(1);
    pub const TIMER_MODE_PWM: e_timer_mode = e_timer_mode(2);
    pub const TIMER_MODE_ONE_SHOT_PULSE: e_timer_mode = e_timer_mode(3);
    pub const TIMER_MODE_TRIANGLE_WAVE_SYMMETRIC_PWM: e_timer_mode = e_timer_mode(4);
    pub const TIMER_MODE_TRIANGLE_WAVE_ASYMMETRIC_PWM: e_timer_mode = e_timer_mode(5);
    pub const TIMER_MODE_TRIANGLE_WAVE_ASYMMETRIC_PWM_MODE3: e_timer_mode = e_timer_mode(6);
    pub const TIMER_MODE_COMPLEMENTARY_PWM_MODE1: e_timer_mode = e_timer_mode(12);
    pub const TIMER_MODE_COMPLEMENTARY_PWM_MODE2: e_timer_mode = e_timer_mode(13);
    pub const TIMER_MODE_COMPLEMENTARY_PWM_MODE3: e_timer_mode = e_timer_mode(14);
    pub const TIMER_MODE_COMPLEMENTARY_PWM_MODE4: e_timer_mode = e_timer_mode(15);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_timer_mode(pub core::ffi::c_uchar);
pub use self::e_timer_mode as timer_mode_t;
impl e_timer_direction {
    pub const TIMER_DIRECTION_DOWN: e_timer_direction = e_timer_direction(0);
    pub const TIMER_DIRECTION_UP: e_timer_direction = e_timer_direction(1);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_timer_direction(pub core::ffi::c_uchar);
pub use self::e_timer_direction as timer_direction_t;
impl e_timer_source_div {
    pub const TIMER_SOURCE_DIV_1: e_timer_source_div = e_timer_source_div(0);
    pub const TIMER_SOURCE_DIV_2: e_timer_source_div = e_timer_source_div(1);
    pub const TIMER_SOURCE_DIV_4: e_timer_source_div = e_timer_source_div(2);
    pub const TIMER_SOURCE_DIV_8: e_timer_source_div = e_timer_source_div(3);
    pub const TIMER_SOURCE_DIV_16: e_timer_source_div = e_timer_source_div(4);
    pub const TIMER_SOURCE_DIV_32: e_timer_source_div = e_timer_source_div(5);
    pub const TIMER_SOURCE_DIV_64: e_timer_source_div = e_timer_source_div(6);
    pub const TIMER_SOURCE_DIV_128: e_timer_source_div = e_timer_source_div(7);
    pub const TIMER_SOURCE_DIV_256: e_timer_source_div = e_timer_source_div(8);
    pub const TIMER_SOURCE_DIV_512: e_timer_source_div = e_timer_source_div(9);
    pub const TIMER_SOURCE_DIV_1024: e_timer_source_div = e_timer_source_div(10);
    pub const TIMER_SOURCE_DIV_8192: e_timer_source_div = e_timer_source_div(13);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct e_timer_source_div(pub core::ffi::c_uchar);
pub use self::e_timer_source_div as timer_source_div_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_timer_info {
    pub count_direction: timer_direction_t,
    pub clock_frequency: u32,
    pub period_counts: u32,
}
pub type timer_info_t = st_timer_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_timer_status {
    pub counter: u32,
    pub state: timer_state_t,
}
pub type timer_status_t = st_timer_status;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_timer_cfg {
    pub mode: timer_mode_t,
    pub period_counts: u32,
    pub source_div: timer_source_div_t,
    pub duty_cycle_counts: u32,
    pub channel: u8,
    pub cycle_end_ipl: u8,
    pub cycle_end_irq: IRQn_Type,
    pub p_callback:
        ::core::option::Option<unsafe extern "C" fn(p_args: *mut timer_callback_args_t)>,
    pub p_context: *mut core::ffi::c_void,
    pub p_extend: *const core::ffi::c_void,
}
pub type timer_cfg_t = st_timer_cfg;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_timer_api {
    pub open: ::core::option::Option<
        unsafe extern "C" fn(p_ctrl: *mut timer_ctrl_t, p_cfg: *const timer_cfg_t) -> fsp_err_t,
    >,
    pub start: ::core::option::Option<unsafe extern "C" fn(p_ctrl: *mut timer_ctrl_t) -> fsp_err_t>,
    pub stop: ::core::option::Option<unsafe extern "C" fn(p_ctrl: *mut timer_ctrl_t) -> fsp_err_t>,
    pub reset: ::core::option::Option<unsafe extern "C" fn(p_ctrl: *mut timer_ctrl_t) -> fsp_err_t>,
    pub enable:
        ::core::option::Option<unsafe extern "C" fn(p_ctrl: *mut timer_ctrl_t) -> fsp_err_t>,
    pub disable:
        ::core::option::Option<unsafe extern "C" fn(p_ctrl: *mut timer_ctrl_t) -> fsp_err_t>,
    pub periodSet: ::core::option::Option<
        unsafe extern "C" fn(p_ctrl: *mut timer_ctrl_t, period: u32) -> fsp_err_t,
    >,
    pub dutyCycleSet: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut timer_ctrl_t,
            duty_cycle_counts: u32,
            pin: u32,
        ) -> fsp_err_t,
    >,
    pub compareMatchSet: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut timer_ctrl_t,
            compare_match_value: u32,
            match_channel: timer_compare_match_t,
        ) -> fsp_err_t,
    >,
    pub infoGet: ::core::option::Option<
        unsafe extern "C" fn(p_ctrl: *mut timer_ctrl_t, p_info: *mut timer_info_t) -> fsp_err_t,
    >,
    pub statusGet: ::core::option::Option<
        unsafe extern "C" fn(p_ctrl: *mut timer_ctrl_t, p_status: *mut timer_status_t) -> fsp_err_t,
    >,
    pub callbackSet: ::core::option::Option<
        unsafe extern "C" fn(
            p_ctrl: *mut timer_ctrl_t,
            p_callback: ::core::option::Option<
                unsafe extern "C" fn(arg1: *mut timer_callback_args_t),
            >,
            p_context: *mut core::ffi::c_void,
            p_callback_memory: *mut timer_callback_args_t,
        ) -> fsp_err_t,
    >,
    pub close: ::core::option::Option<unsafe extern "C" fn(p_ctrl: *mut timer_ctrl_t) -> fsp_err_t>,
}
pub type timer_api_t = st_timer_api;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct st_timer_instance {
    pub p_ctrl: *mut timer_ctrl_t,
    pub p_cfg: *const timer_cfg_t,
    pub p_api: *const timer_api_t,
}
pub type timer_instance_t = st_timer_instance;
